services:
  nginx:
    build: .
    image: nginx-home
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    ports:
      - "3003:80"
